captainVersion: 4
services:
    $$cap_appname:
        image: marcopeg/docker-vacuum
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        environment:
            VACUUM_RULES: $$cap_pg_rules
            VACUUM_INTERVAL: $$cap_pg_interval
            LOG_LEVEL: $$cap_pg_log
        caproverExtra:
            notExposeAsWebApp: 'true'
caproverOneClickApp:
    variables:
        - id: $$cap_pg_rules
          label: Custom rules.
          defaultValue: "[{\\\"match\\\":\\\"(.*)\\\",\\\"retain\\\":2}]"
          description: 'JSON stringified object custom rules. Keys include "match" and "retain".'
          validRegex: /.{0,}/
        - id: $$cap_pg_interval
          label: Interval
          defaultValue: '600000'
          description: 'How often should the cleanup activity will take place?'
          validRegex: /.{0,}/
        - id: $$cap_pg_log
          label: Log Level
          defaultValue: 'info'
          description: 'Options are error, info, verbose, debug.'
          validRegex: /.{0,}/
    instructions:
        start: >-
            Docker Vacuum is a small DevOps utility that runs on your production server as a container and keeps disk usage under control.
            Docker Vacuum prunes the system every now and then (10 minutes by default) and applies your custom rules so to remove unused images with a date-based retention policy.
        end: 'Docker Vacuum will now prune the system from dangling resources and also delete images based on your custom rules.'
    displayName: Docker Vacuum
    isOfficial: true
    description: A small DevOps utility that runs on your production server as a container and keeps disk usage under control.
    documentation: Taken from https://marcopeg.com/2019/docker-vacuum
